apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: hello-world
  templates:
  - name: hello-world
    dag:
      tasks:
        - name: call-print-message
          templateRef:
            name: workflow-template-1
            template: print-message
          arguments:
            parameters:
            - name: message
              value: "hello world"