apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: workflow-template-random-fail-template
spec:
  templates:
  - name: random-fail-template
    retryStrategy:
      limit: 10
    container:
      image: python:alpine3.6
      command: [python, -c]
      # fail with a 75% probability
      args: ["import random; import sys; exit_code = random.choice([0, 1, 0, 1]); sys.exit(exit_code)"]
